tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SFENGINEERING-DEXQA6
      user: gtmteam
      role: accountadmin
      database: charlie_test
      schema: dev
      warehouse: charlie_test
    prod:
      type: snowflake
      account: SFENGINEERING-DEXQA6
      user: gtmteam
      role: accountadmin
      database: charlie_test
      schema: prod
      warehouse: charlie_test